
### requisição com Bearer token
GET http://localhost:8080/medicos
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmEuc291emFAdm9sbC5tZWQiLCJpc3MiOiJBUEkgVm9sbC5tZWQiLCJpZCI6MSwiZXhwIjoxNzMyMjI1MDg4fQ.8PvxZaxDqeUbBzzTr6hFw0hwxt7Hj4YWon1IexgBod8
Content-Type: application/json