
GET http://localhost:8080/pacientes
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmEuc291emFAdm9sbC5tZWQiLCJpc3MiOiJBUEkgVm9sbC5tZWQiLCJpZCI6MSwiZXhwIjoxNzMyMDUxNDA5fQ.22g1CZAuOhyUPiQliZnXYAo0IpxCWOE19aEc1u06dBI

Content-Type: application/json
