
GET http://localhost:8080/pacientes
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmEuc291emFAdm9sbC5tZWQiLCJpc3MiOiJBUEkgVm9sbC5tZWQiLCJpZCI6MSwiZXhwIjoxNzMxOTgyMzU1fQ.VFAcwAr0EryTCnqdwYAnPRdHxuoczefB2FoyzL-BI0c
Content-Type: application/json
