
GET http://localhost:8080/pacientes
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmEuc291emFAdm9sbC5tZWQiLCJpc3MiOiJBUEkgVm9sbC5tZWQiLCJpZCI6MSwiZXhwIjoxNzMxNzk0MTc3fQ.oID1JcHcfT4CoXPIAN-7qrlhfXp3l9pVS3uSWTzNZFE
Content-Type: application/json
