
POST http://localhost:8080/medicos
Content-Type: application/json
Authorization: Bearer:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmEuc291emFAdm9sbC5tZWQiLCJpc3MiOiJBUEkgVm9sbC5tZWQiLCJpZCI6MSwiZXhwIjoxNzMzMzQ2MTQ1fQ.24x5UTGcv4A05LeyHlhXHFY_E8oV3BhxyoJy45PS6v4

{
"nome": "Gabriel Milano",
"email": "gabriel.milano@voll.med",
"crm": "21678",
  "telefone": "5192222222",
"especialidade": "DERMATOLOGIA",
"endereco": {
    "logradouro": "rua 1",
    "bairro": "bairro",
    "cep": "45345678",
    "cidade": "Brasilia",
    "uf": "DF",
    "numero": "1"

    }
}