
POST http://localhost:8080/medicos
Content-Type: application/json

{
"nome": "Gabriel Milano",
"email": "gabriel.milano@voll.med",
"crm": "21678",
  "telefone": "5192222222",
"especialidade": "DERMATOLOGIA",
"endereco": {
    "logradouro": "rua 1",
    "bairro": "bairro",
    "cep": "45345678",
    "cidade": "Brasilia",
    "uf": "DF",
    "numero": "1"

    }
}