
POST http://localhost:8080/pacientes
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmEuc291emFAdm9sbC5tZWQiLCJpc3MiOiJBUEkgVm9sbC5tZWQiLCJpZCI6MSwiZXhwIjoxNzMzMzQ2MTQ1fQ.24x5UTGcv4A05LeyHlhXHFY_E8oV3BhxyoJy45PS6v4
Content-Type: application/json

{
  "nome": "João bala",
  "email": "joao.bala@email.com",
  "telefone": "(11)955555-1234",
  "cpf": "234.981.789-13",
  "addressPatient": {
    "logradouro": "Rua Exemplo",
    "bairro": "Centro",
    "cep": "12345678",
    "cidade": "São Paulo",
    "uf": "SP",
    "numero": "300",
    "complemento": "Apto 100"
  }
}