
POST http://localhost:8080/consultas
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmEuc291emFAdm9sbC5tZWQiLCJpc3MiOiJBUEkgVm9sbC5tZWQiLCJpZCI6MSwiZXhwIjoxNzMzMzQ2MTQ1fQ.24x5UTGcv4A05LeyHlhXHFY_E8oV3BhxyoJy45PS6v4
Content-Type: application/json

{
"idPatient": 1,
"idDoctor": 1,
"data":"2024-12-05T10:00"
}

