
POST http://localhost:8080/medicos
Content-Type: application/json

{
"nome": "Maria  Gasolina",
"email": "maria.gasolina@voll.med",
"crm": "45678",
  "telefone": "5196666666",
"especialidade": "DERMATOLOGIA",
"endereco": {
    "logradouro": "rua 1",
    "bairro": "bairro",
    "cep": "45345678",
    "cidade": "Brasilia",
    "uf": "DF",
    "numero": "1"

    }
}