
POST http://localhost:8080/pacientes
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmEuc291emFAdm9sbC5tZWQiLCJpc3MiOiJBUEkgVm9sbC5tZWQiLCJpZCI6MSwiZXhwIjoxNzMxOTgzOTEzfQ.0xVAAykiZBbWolJsky2tRnlTWPF8ZGnEgBmZZ_dcSGo
Content-Type: application/json

{
  "nome": "Maria Silva",
  "email": "maria.silva@email.com",
  "telefone": "(11)988888-9999",
  "cpf": "423.456.789-00",
  "addressPatient": {
    "logradouro": "Rua Exemplo",
    "bairro": "Centro",
    "cep": "12345678",
    "cidade": "São Paulo",
    "uf": "SP",
    "numero": "123",
    "complemento": "Apto 45"
  }
}