services:
  vollmed:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-vollmed:3306/vollmed
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      mysql-vollmed:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  mysql-vollmed:
    image: mysql:8.0
    container_name: mysql-vollmed
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vollmed
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network
    restart: unless-stopped

  mysql-test:
    image: mysql:8.0
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_vollmed_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
    restart: unless-stopped
    profiles:
      - test

networks:
  app-network:
    driver: bridge
